verify after a CI build that the dist folder actually has the .so or .dll files ( when a godot export silently fails then they are missing usually )

diff --git a/.github/workflows/build-distributables.yaml b/.github/workflows/build-distributables.yaml
--- a/.github/workflows/build-distributables.yaml
+++ b/.github/workflows/build-distributables.yaml
@@ -34,10 +34,6 @@ jobs:
           cache: 'pip'
       - name: Install scons
         run: python3 -m pip install scons==4.4.0
-      - name: verify scons
-        run: scons --version
-      - name: hello
-        run: echo "$(git describe --always)"
       - name: build linux so
         run: scons platform=linux -j$(nproc) godot_editor_dir=$GODOT_EDITOR_DIR
       - name: build windows dll
@@ -51,10 +47,14 @@ jobs:
         run: $GODOT_EDITOR_DIR/Godot_linux.x86_64 --headless --path $GITHUB_WORKSPACE --export-debug "Linux/X11" $LINUX_OUTPUT_DIRNAME/app-linux-demo.x86_64
       - name: Export Windows Build
         run: $GODOT_EDITOR_DIR/Godot_linux.x86_64 --headless --path $GITHUB_WORKSPACE --export-debug "Windows Desktop" $WINDOWS_OUTPUT_DIRNAME/app-windows-demo.exe
+      - name: Verify Linux Build
+        run: if [[ $(find $LINUX_OUTPUT_DIRNAME -type f -name "*.dll" -or -name "*.so" | wc -l) -ge 1 ]]; then echo '.dll or .so found'; else echo '.dll or .so NOT found'; exit 1; fi 
       - uses: actions/upload-artifact@v3
         with:
           name: app-linux-demo-${{ env.TAG }}.zip
           path: ${{ env.LINUX_OUTPUT_DIRNAME }}
+      - name: Verify Windows Build
+        run: if [[ $(find $WINDOWS_OUTPUT_DIRNAME -type f -name "*.dll" -or -name "*.so" | wc -l) -ge 1 ]]; then echo '.dll or .so found'; else echo '.dll or .so NOT found'; exit 1; fi 
       - uses: actions/upload-artifact@v3
         with:
           name: app-windows-demo-${{ env.TAG }}.zip
